### ISSUE TITLE
Create integration tests for "Age" rule

### ISSUE THREAD

**Issue by williamespindola** [Respect/Validation#510] opened 2015-10-17 17:51 UTC

**Comment by williamespindola** [comment] 2015-10-22 05:56
Hello body I'm trying to test this rule in the with this conditions
```php
v::age(10, 50)->assert('9 years ago');
```
Here I have this message `\-"9 years ago" must be lower than or equals "2005-10-22 23:59:59"` The message should't be `greater than` instead lower?

**Comment by batusa** [comment] 2015-10-22 11:31
`greater than` would decrease the age. I think the message is correct.

**Comment by henriquemoody** [comment] 2015-10-22 14:10
That's probably a more user friendly message, the problem is that `age()` rule uses `Min` and `Max` rule, that's why this disgusting message.

**Comment by williamespindola** [comment] 2015-10-23 20:53
Correct @batusa now I understand, if the assert is greater than 2006 it will be lower of 10. But I need to be between 10 and 50 so lower than 2006.

Yes @henriquemoody this message is vary complicated. Can we try this:
`"9 years ago" is not between 10 and 50 and must be lower than or equals "2005-10-22 23:59:59" to stay between 10 and 50`

**Comment by williamespindola** [comment] 2015-11-07 17:46
Hei guys the tests for this issue has been implemented. We will work with the message on the issue? About my opinion with the error message you have some opnion?

**Comment by henriquemoody** [comment] 2015-11-09 08:56
Fixed by #592

**Closed by henriquemoody** 2015-11-09 08:56 UTC
Labels: Easy Pick, TestFest
