### ISSUE TITLE
The Key validator return true if the array is an empty string

### ISSUE THREAD

**Issue by edhelas** [Respect/Validation#440] opened 2015-10-08 13:23 UTC
> $array = "";
> Validator::key('my_key')->validate($array);
> TRUE

Validation version: 0.9.3
Caused by https://github.com/Respect/Validation/blob/0.9/library/Rules/AbstractRelated.php#L68
This seems to be fixed in master 
Can you port this fix to the stable branches ?

**Comment by henriquemoody** [comment] 2015-10-08 13:51
Hey, @edhelas, that's not a bug, that's is a feature:

![bug-feature](https://cloud.githubusercontent.com/assets/154023/10368094/0f3c19d8-6daa-11e5-984f-9446af41e9f9.png)

Or [docs says](http://respect.github.io/Validation/docs/#input-optional):
> All validators treat input as optional and will accept empty string input as valid

However, as you said this was changed on master, but it cannot be changed on <0.9.x versions because it breaks back compatibility.

The [version 1.0](https://github.com/Respect/Validation/blob/master/CHANGELOG.md#100---2015-10-24), the current master, will be released on Oct 24th.

**Closed by henriquemoody** 2015-10-08 13:51 UTC

**Comment by edhelas** [comment] 2015-10-08 13:56
Thanks for the quick answer. So I'll put notEmpty() for the moment :)
